@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/textes HTTP/1.1

###
GET {{baseUrl}}/textes?level=hard HTTP/1.1

###
GET  {{baseUrl}}/textes/726aefb3-2578-46b7-8dfc-1cb6561322d0 HTTP/1.1

###
POST  {{baseUrl}}/textes HTTP/1.1
Content-Type: application/json

{
    "content":"xs jecczacz m'appelle kim",
    "level":"medium"
}

###
DELETE {{baseUrl}}/textes/5819b2a8-b94e-4bcf-9f9f-43d8b2cde23c HTTP/1.1

###
PUT {{baseUrl}}/textes/7bb98edc-84a9-4737-87d1-e8b3f5230fcd HTTP/1.1
Content-Type: application/json

{
    "content":"fUnable to compile TypeScript:",
    "level":"easy"
}

