@baseUrl = http://localhost:3000

###try to login an unknown user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "unknown",
    "password": "admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "manager",
    "password": "manager"
}

###login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "manager",
    "password": "manager"
}