@baseUrl = http://localhost:3000

###
GET http://localhost:3000/films?minimum-duration=110  HTTP/1.1

###
GET http://localhost:3000/films?sortTitle=asc  HTTP/1.1

###
GET http://localhost:3000/films?sortDuration=asc  HTTP/1.1

###
GET http://localhost:3000/films HTTP/1.1

###
GET http://localhost:3000/films/5 HTTP/1.1

###
POST http://localhost:3000/films HTTP/1.1
Content-Type: application/json

{
    "title":"pauline",
    "director":"Kim Bryere",
    "duration":110,
    "budget":10000
}

###
DELETE {{baseUrl}}/films/1 HTTP/1.1

###
PATCH  {{baseUrl}}/films/3 HTTP/1.1
Content-Type: application/json

{
    "title":"Kim Bryere"
}

###
PUT {{baseUrl}}/films/10 HTTP/1.1
Content-Type: application/json

{
    "title":"Queen of tears",
    "director":"Kim d",
    "duration":120,
    "budget":1000,
    "description":"film d'horeur",
    "imageUrl":"http;//conjuring.be"
}
